services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\FanCourierBundle\ConfigProvider: ~
    Answear\FanCourierBundle\Client\Client: ~
    Answear\FanCourierBundle\Logger\FanCourierLogger:
        shared: false

    Answear\FanCourierBundle\Client\RequestTransformerInterface: '@Answear\FanCourierBundle\Client\RequestTransformer'
