services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\FanCourierBundle\:
        resource: '../../../src/{Client,Service,RequestTransformer,Request,Serializer}'

    Answear\FanCourierBundle\ConfigProvider: ~

    Answear\FanCourierBundle\Logger\FanCourierLogger:
        shared: false

    Answear\FanCourierBundle\Client\RequestTransformerInterface: '@Answear\FanCourierBundle\Client\RequestTransformer'
